name: ai_x2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - nodejs=18
  - npm
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - openai==1.3.0
    - httpx==0.25.0
    - python-dotenv==1.0.0
    - python-multipart==0.0.6

